[tool.poetry]
name = "eds-pseudonymisation"
version = "0.1.0"
description = ""
authors = ["Basile Dura <basile.dura-ext@aphp.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
spacy = {extras = ["cuda102"], version = "^3.3.0"}
spacy-transformers = "^1.1.5"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
jupytext = "^1.13.8"
pre-commit = "^2.18.1"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-html = "^3.1.1"
griffe = "^0.19.0"
Jinja2 = ">=2.10.2<=3.0.3"
mike = "^1.1.2"
mkdocs-autorefs = "0.3.1"
mkdocs-bibtex = "^2.0.3"
mkdocs-charts-plugin = "^0.0.8"
mkdocs-gen-files = "^0.3.4"
mkdocs-img2fig-plugin = "^0.9.3"
mkdocs-literate-nav = "^0.4.1"
mkdocs-material = "^8.2.8"
mkdocs-section-index = "^0.3.4"
mkdocstrings = "^0.18.1"
mkdocstrings-python = "^0.6.6"
streamlit = "^1.8.1"
mypy = "^0.950"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 10
exclude = ["docs", "build", "tests"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
omit-covered-files = false

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
plugins = "pydantic.mypy"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
